/**
 * Shell completions.
 *
 * The scripts stay deliberately thin: anything that needs to know about the
 * repository calls back into `nav __complete`, so completion behavior lives in
 * one implementation rather than three shell dialects.
 */

import { existsSync, mkdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { homedir } from "node:os";
import { basename, dirname, join } from "node:path";

export const SHELLS = ["bash", "zsh", "fish"] as const;
export type Shell = (typeof SHELLS)[number];

export function isShell(value: string): value is Shell {
  return (SHELLS as readonly string[]).includes(value);
}

/** Guess the user's shell from `$SHELL`, defaulting to bash. */
export function detectShell(env: NodeJS.ProcessEnv): Shell {
  const name = basename(env.SHELL ?? "");
  return isShell(name) ? name : "bash";
}

/** Where a shell looks for per-user completion scripts. */
export function completionPath(shell: Shell, env: NodeJS.ProcessEnv): string {
  const home = env.HOME ?? homedir();
  const dataHome = env.XDG_DATA_HOME ?? join(home, ".local", "share");
  const configHome = env.XDG_CONFIG_HOME ?? join(home, ".config");
  switch (shell) {
    case "bash":
      return join(dataHome, "bash-completion", "completions", "nav");
    case "zsh":
      return join(dataHome, "zsh", "site-functions", "_nav");
    default:
      return join(configHome, "fish", "completions", "nav.fish");
  }
}

/** Extra advice printed after installing, where a shell needs configuration. */
export function completionNote(shell: Shell, path: string): string | null {
  if (shell !== "zsh") return null;
  return `zsh needs ${dirname(path)} on its fpath; add this to ~/.zshrc if it is not:\n  fpath=(${dirname(path)} $fpath)`;
}

export function completionScript(shell: Shell): string {
  switch (shell) {
    case "bash":
      return BASH;
    case "zsh":
      return ZSH;
    default:
      return FISH;
  }
}

export function installCompletions(shell: Shell, env: NodeJS.ProcessEnv): string {
  const path = completionPath(shell, env);
  mkdirSync(dirname(path), { recursive: true });
  writeFileSync(path, completionScript(shell), "utf8");
  return path;
}

export function uninstallCompletions(shell: Shell, env: NodeJS.ProcessEnv): string | null {
  const path = completionPath(shell, env);
  if (!existsSync(path)) return null;
  // Only remove a file this tool wrote.
  if (!readFileSync(path, "utf8").includes("nav __complete")) return null;
  rmSync(path, { force: true });
  return path;
}

const BASH = `# bash completion for nav (navbook). Generated by 'nav install --completions'.
_nav_complete() {
  local cur prev
  cur="\${COMP_WORDS[COMP_CWORD]}"
  prev="\${COMP_WORDS[COMP_CWORD-1]}"
  local reply
  reply="$(nav __complete "\${COMP_WORDS[@]:1:COMP_CWORD-1}" 2>/dev/null)"
  COMPREPLY=($(compgen -W "\${reply}" -- "\${cur}"))
  return 0
}
complete -F _nav_complete nav
`;

const ZSH = `#compdef nav
# zsh completion for nav (navbook). Generated by 'nav install --completions'.
_nav() {
  local -a candidates
  candidates=(\${(f)"$(nav __complete \${words[2,CURRENT-1]} 2>/dev/null)"})
  _describe 'nav' candidates
}
compdef _nav nav
`;

const FISH = `# fish completion for nav (navbook). Generated by 'nav install --completions'.
function __nav_complete
  set -l tokens (commandline -opc)
  nav __complete $tokens[2..-1] 2>/dev/null
end
complete -c nav -f -a '(__nav_complete)'
`;
