/**
 * Client types generated from the schema this client is built against.
 *
 * The server's schema alone, and no plugin's. This package is the host: it
 * draws issues and pull requests, and it must build whether or not any plugin
 * is installed. A plugin's own documents are generated by the plugin, against
 * the composed schema, in its own package (spec 06 §6.3) — which is why the
 * host's fragments here select `ext` rather than naming a field somebody else
 * added.
 *
 * It is read from the package rather than copied, so there is one contract and
 * no drift: an incompatible change to the API breaks this package's type check
 * rather than its users.
 *
 * As on the server, the generated files are committed and CI checks they are
 * current (`codegen:check`). Enums come out as string-literal unions because
 * `erasableSyntaxOnly` forbids TypeScript enums, and fragment masking is off:
 * the components here are small enough that plain result types are clearer
 * than threading `useFragment` through every one of them.
 */

import type { CodegenConfig } from "@graphql-codegen/cli";

const config: CodegenConfig = {
  schema: ["../server/schema.graphql"],
  // Every operation lives in `app/graphql/`, never inline in a component, so
  // that this glob is the whole story and a fragment is reusable by name.
  documents: ["app/graphql/**/*.ts"],
  generates: {
    "src/generated/gql/": {
      preset: "client",
      presetConfig: { fragmentMasking: false },
      config: {
        useTypeImports: true,
        enumsAsTypes: true,
        // `ext` is whatever the loaded plugins put on an entity, so the client
        // gets a map it must look into rather than a shape it can trust — and
        // both packages spell it the same way, or a row this layer built could
        // not be handed to one of the host's components.
        scalars: { JSON: "Record<string, unknown>" },
      },
    },
  },
};

export default config;
